config/routes.rb
Rails.application.routes.draw do
  resources :word_classes
  resources :books
  resources :pairs
  devise_for :users
  resources :users

  match '/api', :to => "pairs#add_pair", :as => :add_pair, via: [:get, :post]
  match '/about', :to => "pairs#about", :as => :about, via: [:get, :post]

  root to: 'users#index'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if 
        can :manage, :all
    else
      
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :pairs
end

app/models/pair.rb
class Pair < ActiveRecord::Base
  has_and_belongs_to_many :books
  has_and_belongs_to_many :word_classes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :rememberable, :trackable, :validatable
         
end

app/models/word_class.rb
class WordClass < ActiveRecord::Base
  has_and_belongs_to_many :pairs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # load_and_authorize_resource
  load_and_authorize_resource :unless => :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => "Неправильный урл."
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.all
  end

  # GET /books/1
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to books_path, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:name, :publisher, :year, :author)
    end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  before_action :set_pair, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, :only => [:add_pair]
  skip_before_filter :verify_authenticity_token, :only => [:add_pair]
  
  # GET /pairs
  def index
    @pairs = Pair.all
  end

  # GET /pairs/1
  def show
  end

  # GET /pairs/new
  def new
    @pair = Pair.new
  end

  # GET /pairs/1/edit
  def edit
  end

  # POST /pairs
  def create
    @pair = Pair.new(pair_params)

    if @pair.save
      redirect_to pairs_path, notice: 'Pair was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pairs/1
  def update
    if @pair.update(pair_params)
      redirect_to pairs_path, notice: 'Pair was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pairs/1
  def destroy
    @pair.destroy
    redirect_to pairs_url, notice: 'Pair was successfully destroyed.'
  end

  def add_pair
    par = params.permit(:word, :translate1, :translate2, :translate3, :translate4, word_class_ids: [], book_ids: [])
    @pair = Pair.new(par)

    if @pair.save
      render text: "Ok"
    else
      render text: "Wrong params"
    end
  end

  def about

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pair
      @pair = Pair.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pair_params
      params.require(:pair).permit(:word, :translate1, :translate2, :translate3, :translate4, word_class_ids: [], book_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :current_password, :password, :password_confirmation)
    end
end

app/controllers/word_classes_controller.rb
class WordClassesController < ApplicationController
  before_action :set_word_class, only: [:show, :edit, :update, :destroy]

  # GET /word_classes
  def index
    @word_classes = WordClass.all
  end

  # GET /word_classes/1
  def show
  end

  # GET /word_classes/new
  def new
    @word_class = WordClass.new
  end

  # GET /word_classes/1/edit
  def edit
  end

  # POST /word_classes
  def create
    @word_class = WordClass.new(word_class_params)

    if @word_class.save
      redirect_to word_classes_path, notice: 'Word class was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /word_classes/1
  def update
    if @word_class.update(word_class_params)
      redirect_to word_classes_path, notice: 'Word class was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /word_classes/1
  def destroy
    @word_class.destroy
    redirect_to word_classes_url, notice: 'Word class was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word_class
      @word_class = WordClass.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def word_class_params
      params.require(:word_class).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/word_classes_helper.rb
module WordClassesHelper
end

app/views/books/_form.html.haml
= simple_form_for @book, :html => { :class => 'form-horizontal' } do |f|
  .row
    .col-md-6
      = f.input :name, label: "Название"
  .row
    .col-md-6
      = f.input :publisher, label: "Издательство"
  .row
    .col-md-6
      = f.input :year, label: "Год"
  .row
    .col-md-6
      = f.input :author, label: "Автор"
  .row
    .col-md-6
      = f.button :submit, "Сохранить", :class => 'btn-primary'
      = link_to "Отмена", books_path, :class => 'btn btn-default'

app/views/books/edit.html.haml
- model_class = Book
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/books/index.html.haml
- model_class = Book
.page-header
  %h1
    Учебники
%br
= link_to "Добавить", new_book_path, :class => 'btn btn-primary'
%br
%br
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th
        Название
      %th
        Издательство
      %th
        Год
      %th
        Автор
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @books.each do |book|
      %tr
        %td= link_to book.id, book_path(book)
        %td= book.name
        %td= book.publisher
        %td= book.year
        %td= book.author
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_book_path(book), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), book_path(book), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/books/new.html.haml
- model_class = Book
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/books/show.html.haml
- model_class = Book
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @book.name
%p
  %strong= model_class.human_attribute_name(:publisher) + ':'
  %br
  = @book.publisher
%p
  %strong= model_class.human_attribute_name(:year) + ':'
  %br
  = @book.year
%p
  %strong= model_class.human_attribute_name(:author) + ':'
  %br
  = @book.author


= link_to t('.back', :default => t("helpers.links.back")), books_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_book_path(@book), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), book_path(@book), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Simply"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "Simply", root_path, class: "navbar-brand"
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            -if current_user
              %li= link_to "Словарь", pairs_path
              %li= link_to "Учебники", books_path
              %li= link_to "Часть речи", word_classes_path
              %li= link_to "Пользователи", users_path
              %li= link_to "Полезное", about_path
          %ul.nav.navbar-nav.pull-right
            -if current_user
              %li= link_to "Выйти", destroy_user_session_path, method: :delete
            -else
              %li= link_to "Войти", new_user_session_path
    .container
      .row
        .col-lg-12  
          = bootstrap_flash
          = yield
        / .col-lg-3
        /   .well.sidebar-nav
        /     %h3 Sidebar
        /     %ul.nav.nav-list
        /       %li.nav-header Sidebar
        /       %li= link_to "Link 1", "/path1"
        /       %li= link_to "Link 2", "/path2"
        /       %li= link_to "Link 3", "/path3"
      / %footer
      /   %p &copy; Company 2015

app/views/pairs/_form.html.haml
.container
= simple_form_for @pair, :html => { :class => 'form-horizontal' } do |f|
  .row
    .col-md-6
      = f.input :word, label: "Слово"
  .row
    .col-md-6
      = f.input :translate1, label: "Перевод 1"
  .row
    .col-md-6
      = f.input :translate2, label: "Перевод 2"
  .row
    .col-md-6
      = f.input :translate3, label: "Перевод 3"
  .row
    .col-md-6
      = f.input :translate4, label: "Перевод 4"
  .row
    .col-md-6
      = f.association :books, collection: Book.order(:name), label: "Учебники"
  .row
    .col-md-6
      = f.association :word_classes, collection: WordClass.order(:name), label: "Части речи"
  .row
    .col-md-6
      = f.button :submit, "Сохранить", :class => 'btn-primary'
      = link_to "Отмена", pairs_path, :class => 'btn btn-default'

app/views/pairs/about.html.haml
.container
  %b
    Пример API запроса для добавления в словарь:
  %br
  %br
  http://simply.su/api?book_ids[]=2&book_ids[]=1&translate1=перевод1&translate2=перевод2&translate3=&translate4=&word=book&word_class_ids[]=3&word_class_ids[]=2

app/views/pairs/edit.html.haml
- model_class = Pair
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/pairs/index.html.haml
- model_class = Pair
.page-header
  %h1
    Словарь
%br
= link_to "Добавить", new_pair_path, :class => 'btn btn-primary'
%br
%br
%table.table.table-striped
  %thead
    %tr
      %th
        №
      %th
        Слово
      %th
        Перевод 1
      %th
        Перевод 2
      %th
        Перевод 3
      %th
        Перевод 4
      %th
        Часть речи
      %th
        Учебник
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @pairs.each_with_index do |pair, i|
      %tr
        %td= i+1
        %td= pair.word
        %td= pair.translate1
        %td= pair.translate2
        %td= pair.translate3
        %td= pair.translate4
        %td
          - pair.word_classes.each do |wc|
            = wc.name
            %br
        %td
          - pair.books.each do |book|
            =book.name
            %br
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_pair_path(pair), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), pair_path(pair), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/pairs/new.html.haml
- model_class = Pair
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .row
    .col-md-4
      = f.input :email
  .row
    .col-md-4
      = f.input :password
  .row
    .col-md-4
      = f.input :password_confirm
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:email)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip


= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/word_classes/_form.html.haml
.container
  = simple_form_for @word_class, :html => { :class => 'form-horizontal' } do |f|
    .row
      .col-md-6
        = f.input :name, label: "Название"
    .row
      .col-md-6
        = f.button :submit, "Сохранить", :class => 'btn-primary'
        = link_to "Отмена", word_classes_path, :class => 'btn btn-default'

app/views/word_classes/edit.html.haml
- model_class = WordClass
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/word_classes/index.html.haml
- model_class = WordClass
.page-header
  %h1
    Части речи
%br
= link_to "Добавить", new_word_class_path, :class => 'btn btn-primary'
%br
%br
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th
        Название
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @word_classes.each do |word_class|
      %tr
        %td= link_to word_class.id, word_class_path(word_class)
        %td= word_class.name
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_word_class_path(word_class), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), word_class_path(word_class), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/word_classes/new.html.haml
- model_class = WordClass
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/word_classes/show.html.haml
- model_class = WordClass
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @word_class.name


= link_to t('.back', :default => t("helpers.links.back")), word_classes_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_word_class_path(@word_class), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), word_class_path(@word_class), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'